/**
 * genetics-catalog.ts
 *
 * Catálogo de REFERENCIA (solo lectura), igual en espíritu a
 * cultivation-reference.ts. Contiene datos publicados por el
 * fabricante (nombre, tipo, floración, THC, notas) para que el
 * usuario los consulte como ayuda visual al cargar SU propia
 * genética a mano en el formulario manual.
 *
 * IMPORTANTE — se mantiene el mismo límite ya acordado para el
 * proyecto:
 *   - Esto NO calcula fechas de cosecha.
 *   - Esto NO se conecta a un motor que tome estos datos + una
 *     fecha de siembra y devuelva un plan automático de riego,
 *     luz, sustrato o cosecha.
 *   - Es texto informativo que se muestra al lado de un formulario
 *     que el usuario completa a mano (nombre, tipo, sus propias
 *     fechas), igual que en cultivation-reference.ts.
 */

export type GeneticType = "feminized" | "regular" | "autoflowering" | "faster_flowering";
export type GeneticRawFieldValue = string | number | boolean | null;

export interface GeneticReferenceEntry {
  id: string;
  name: string;
  cross: string; // genética / cruza declarada por el fabricante
  type: GeneticType;
  /** Rango de semanas de floración (fotoperiódicas) o ciclo total (autos), como referencia */
  flowering_weeks_range: [number, number];
  thc_percent_range: [number, number];
  effect_notes: string;
  flavor_notes: string;
  /** Campos originales de una fuente tabular importada. Solo lectura; no alimenta calculos. */
  raw_fields?: Record<string, GeneticRawFieldValue>;
  source: string; // referencia de origen del dato
}

export const GENETICS_CATALOG: GeneticReferenceEntry[] = [
  // ---- FEMINIZED ----
  {
    id: "pineapple-larry-og-fem",
    name: "Pineapple Larry OG",
    cross: "Cinderella 99 x Sll OG",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [22, 22],
    effect_notes: "Euforia, felicidad, energía",
    flavor_notes: "Piña, limón, dulce",
    source: "Catálogo BSF 2024",
  },
  {
    id: "rainbows-fem",
    name: "Rainbows",
    cross: "Zkittlez × Zkittlez",
    type: "feminized",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [24, 24],
    effect_notes: "Eufórico estimulante, cerebral, duradero",
    flavor_notes: "Cóctel de frutas, pomelo dulce",
    source: "Catálogo BSF 2024",
  },
  {
    id: "lebron-haze-fem",
    name: "Lebron Haze",
    cross: "(Haze × Haze) × Lemon Thai",
    type: "feminized",
    flowering_weeks_range: [7, 8],
    thc_percent_range: [22, 22],
    effect_notes: "Euforizante, creativo, cerebral, sativo",
    flavor_notes: "Cóctel de frutas, pomelo dulce",
    source: "Catálogo BSF 2024",
  },
  {
    id: "double-cookies-fem",
    name: "Double Cookies",
    cross: "Do-Si-Dos × Cookies Forum Cut",
    type: "feminized",
    flowering_weeks_range: [7, 8],
    thc_percent_range: [27, 27],
    effect_notes: "Felicidad relajante",
    flavor_notes: "Dulce, terroso, galleta, menta",
    source: "Catálogo BSF 2024",
  },
  {
    id: "orange-blossom-fem",
    name: "Orange Blossom",
    cross: "Cali orange × Skunk pre90",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [20, 20],
    effect_notes: "Felicidad, creatividad, euforia",
    flavor_notes: "Mandarina, frutal, cítrico",
    source: "Catálogo BSF 2024",
  },
  {
    id: "blueberry-fem",
    name: "Blueberry",
    cross: "Blueberry S1",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [22, 22],
    effect_notes: "Fuerte, cerebral",
    flavor_notes: "Frutos del bosque, arándano",
    source: "Catálogo BSF 2024",
  },
  {
    id: "moby-d-fem",
    name: "Moby-D",
    cross: "Jack Herer × White Widow",
    type: "feminized",
    flowering_weeks_range: [10, 12],
    thc_percent_range: [19, 19],
    effect_notes: "Euforizante",
    flavor_notes: "Pino, limón, haze",
    source: "Catálogo BSF 2024",
  },
  {
    id: "critical-plus2-fem",
    name: "Critical +2",
    cross: "Big Bud × Skunk",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [20, 20],
    effect_notes: "Potente, sedante, cerebral",
    flavor_notes: "Flores dulces",
    source: "Catálogo BSF 2024",
  },
  {
    id: "slh-fem",
    name: "SLH",
    cross: "Lemon Skunk × Super Silver Haze",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [19, 19],
    effect_notes: "Psicodélico, euforizante",
    flavor_notes: "Pomelo, limón, incienso, pimienta",
    source: "Catálogo BSF 2024",
  },
  {
    id: "gorilla-glue-4-fem",
    name: "Gorilla Glue #4",
    cross: "Chem Sister × Sour Dubb × Chocolate Diesel",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [21, 21],
    effect_notes: "Euforizante, relajante",
    flavor_notes: "Terroso, ácido, chocolate",
    source: "Catálogo BSF 2024",
  },
  {
    id: "gorilla-rainbow-fem",
    name: "Gorilla Rainbow",
    cross: "Gorilla Glue #4 x Rainbows",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [20, 25],
    effect_notes: "Fuerte, calmante, relajante",
    flavor_notes: "Caramelo, afrutado, terroso",
    source: "Catálogo BSF 2024",
  },
  {
    id: "gorilla-white-fem",
    name: "Gorilla White",
    cross: "Gorilla Glue #4 x White Widow",
    type: "feminized",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [25, 25],
    effect_notes: "Fuerte, relajante, psicoactivo",
    flavor_notes: "Terroso, dulce, cítrico",
    source: "Catálogo BSF 2024",
  },
  {
    id: "gorilla-ghost-fem",
    name: "Gorilla Ghost",
    cross: "Gorilla Glue #4 x Ghost OG",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [26, 29],
    effect_notes: "Fuerte, relajante",
    flavor_notes: "Floral, frutos del bosque, cítrico",
    source: "Catálogo BSF 2024",
  },
  {
    id: "gorilla-banana-fem",
    name: "Gorilla Banana",
    cross: "Gorilla Glue #4 x Punch de Banana",
    type: "feminized",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [22, 25],
    effect_notes: "Sedante, somnífero",
    flavor_notes: "Terroso, dulce, banana",
    source: "Catálogo BSF 2024",
  },
  {
    id: "nitro-haze-fem",
    name: "Nitro Haze",
    cross: "Lebron Haze x Black Dómina 98",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [21, 21],
    effect_notes: "Euforizante, equilibrado, cerebral",
    flavor_notes: "Merengue de limón con toques de haze",
    source: "Catálogo BSF 2024",
  },
  {
    id: "skunk-fem",
    name: "Skunk",
    cross: "Skunk S1",
    type: "feminized",
    flowering_weeks_range: [7, 8],
    thc_percent_range: [18, 24],
    effect_notes: "Relajante, sedante",
    flavor_notes: "Frutal, cítrico, queso",
    source: "Catálogo BSF 2024",
  },
  {
    id: "bubble-gum-fem",
    name: "Bubble Gum",
    cross: "Bubblegum S1",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [20, 25],
    effect_notes: "Fuerte, duradero, relajante",
    flavor_notes: "Dulce, chicle de frutilla",
    source: "Catálogo BSF 2024",
  },
  {
    id: "northern-lights-fem",
    name: "Northern Lights",
    cross: "Northern Light S1",
    type: "feminized",
    flowering_weeks_range: [7, 8],
    thc_percent_range: [18, 20],
    effect_notes: "Equilibrado, relajante, sedante",
    flavor_notes: "Terroso, notas frutales, pimienta",
    source: "Catálogo BSF 2024",
  },
  {
    id: "ak47-fem",
    name: "AK 47",
    cross: "Colombian x Mexican x Tai Afgan",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [15, 20],
    effect_notes: "Cerebral, eufórico, calmante",
    flavor_notes: "Dulce, terroso, floral",
    source: "Catálogo BSF 2024",
  },

  // ---- AUTOFLOWERING ---- (ciclo completo expresado en semanas aprox.)
  {
    id: "red-skunk-auto",
    name: "Red Skunk Auto",
    cross: "Skunk",
    type: "autoflowering",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [19, 19],
    effect_notes: "Narcótico, sedante",
    flavor_notes: "Frutos del bosque, dulce",
    source: "Catálogo BSF 2024 (ciclo completo 60-65 días)",
  },
  {
    id: "red-kush-auto",
    name: "Red Kush Auto",
    cross: "Hindu Kush",
    type: "autoflowering",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [18, 18],
    effect_notes: "Relajante, sedante",
    flavor_notes: "Afrutado, terroso",
    source: "Catálogo BSF 2024 (ciclo completo 60-65 días)",
  },
  {
    id: "red-critical-auto",
    name: "Red Critical Auto",
    cross: "Gorilla Glue #4",
    type: "autoflowering",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [20, 20],
    effect_notes: "Potente, sedante, cerebral",
    flavor_notes: "Flores dulces",
    source: "Catálogo BSF 2024 (ciclo completo 60-65 días)",
  },
  {
    id: "amnesia-auto",
    name: "Amnesia Auto",
    cross: "Amnesia Auto × Macho Seleccionado Auto",
    type: "autoflowering",
    flowering_weeks_range: [11, 13],
    thc_percent_range: [19, 19],
    effect_notes: "Potente, físico, activo",
    flavor_notes: "Pino, incienso, haze",
    source: "Catálogo BSF 2024 (ciclo completo 75-90 días)",
  },
  {
    id: "ak-auto",
    name: "AK Auto",
    cross: "AK 47 × Macho Seleccionado Auto",
    type: "autoflowering",
    flowering_weeks_range: [10, 10],
    thc_percent_range: [18, 18],
    effect_notes: "Subidón cerebral, intenso",
    flavor_notes: "Dulce, cítrico, pino",
    source: "Catálogo BSF 2024 (ciclo completo 70 días)",
  },
  {
    id: "lemon-haze-auto",
    name: "Lemon Haze Auto",
    cross: "Jack Herer Auto × Lemon Haze",
    type: "autoflowering",
    flowering_weeks_range: [10, 10],
    thc_percent_range: [18, 18],
    effect_notes: "Subidón cerebral, activo",
    flavor_notes: "Limón, haze, pino",
    source: "Catálogo BSF 2024 (ciclo completo 75 días)",
  },
  {
    id: "og-kush-auto",
    name: "OG Kush Auto",
    cross: "OG Kush",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [18, 18],
    effect_notes: "Potente, físico, mental",
    flavor_notes: "Tierra, pimienta, dulce",
    source: "Catálogo BSF 2024 (ciclo completo 70-75 días)",
  },
  {
    id: "sour-diesel-auto",
    name: "Sour Diesel Auto",
    cross: "Sour Diesel",
    type: "autoflowering",
    flowering_weeks_range: [10, 10],
    thc_percent_range: [22, 22],
    effect_notes: "Físico, mental, equilibrado",
    flavor_notes: "Mandarina, petróleo, madera",
    source: "Catálogo BSF 2024 (ciclo completo 70 días)",
  },
  {
    id: "gorilla-glue-auto",
    name: "Gorilla Glue Auto",
    cross: "Gorilla Glue Auto",
    type: "autoflowering",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [21, 21],
    effect_notes: "Equilibrado, euforizante, relajado",
    flavor_notes: "Dulce, tierra, ponche de frutas",
    source: "Catálogo BSF 2024 (ciclo completo 65 días)",
  },
  {
    id: "blueberry-auto",
    name: "Blueberry Auto",
    cross: "Blueberry Auto",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [20, 20],
    effect_notes: "Subidón cerebral, relajante",
    flavor_notes: "Frutos del bosque, arándano",
    source: "Catálogo BSF 2024 (ciclo completo 70-75 días)",
  },
  {
    id: "orange-blossom-auto",
    name: "Orange Blossom Auto",
    cross: "Orange Blossom × Orange Blossom Auto 4ta gen",
    type: "autoflowering",
    flowering_weeks_range: [11, 11],
    thc_percent_range: [20, 20],
    effect_notes: "Felicidad, energizante",
    flavor_notes: "Mandarina, cítrico, frutal",
    source: "Catálogo BSF 2024 (ciclo completo 75-80 días)",
  },
  {
    id: "pineapple-larry-og-auto",
    name: "Pineapple Larry OG Auto",
    cross: "Pineapple Larry OG x Pineapple Auto 4ta gen",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [23, 23],
    effect_notes: "Estimulante, enérgico",
    flavor_notes: "Dulce, madera, piña madura, limón",
    source: "Catálogo BSF 2024 (ciclo completo 70-75 días)",
  },
  {
    id: "double-cookies-auto",
    name: "Double Cookies Auto",
    cross: "Do-Si-Dos X Girl Scout Cookies Auto",
    type: "autoflowering",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [22, 22],
    effect_notes: "Sedante, relajante, creativo",
    flavor_notes: "Menta dulce, lima fresca, pino",
    source: "Catálogo BSF 2024 (ciclo completo 55-60 días)",
  },

  // ---- FASTER FLOWERING (fotoperiódicas de ciclo corto) ----
  {
    id: "obg-kush-faster",
    name: "OBG Kush",
    cross: "OG Kush",
    type: "faster_flowering",
    flowering_weeks_range: [6, 6],
    thc_percent_range: [22, 22],
    effect_notes: "Sedante, relajante",
    flavor_notes: "Dulce, terroso, picante",
    source: "Catálogo BSF 2024",
  },
  {
    id: "green-tiger-faster",
    name: "Green Tiger",
    cross: "(Early Skunk × Skunk) × Skunk Pre90",
    type: "faster_flowering",
    flowering_weeks_range: [6, 6],
    thc_percent_range: [22, 22],
    effect_notes: "Relajante, creativo",
    flavor_notes: "Limón, cedro",
    source: "Catálogo BSF 2024",
  },
  {
    id: "gorilla-glue-faster",
    name: "Gorilla Glue Faster",
    cross: "Gorilla Glue Faster",
    type: "faster_flowering",
    flowering_weeks_range: [6, 6],
    thc_percent_range: [24, 24],
    effect_notes: "Narcótico, eufórico",
    flavor_notes: "Tierra húmeda, chocolate",
    source: "Catálogo BSF 2024",
  },
  {
    id: "el-gaucho-faster",
    name: "El Gaucho",
    cross: "Sierra Madre x Blue Mountain",
    type: "faster_flowering",
    flowering_weeks_range: [6, 6],
    thc_percent_range: [22, 22],
    effect_notes: "Relajante",
    flavor_notes: "Dulce, afrutado",
    source: "Catálogo BSF 2024",
  },
  // ---- DUTCH PASSION (photoperiod feminized/reference) ----
  {
    id: "white-widow-dp",
    name: "White Widow",
    cross: "Classic F1 White Widow",
    type: "feminized",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [20, 25],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "power-plant-dp",
    name: "Power Plant",
    cross: "Original South African Power Plant",
    type: "feminized",
    flowering_weeks_range: [8, 10],
    thc_percent_range: [18, 20],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "durban-poison-dp",
    name: "Durban Poison",
    cross: "Durban x Unknown Indica",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [18, 22],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "mazar-dp",
    name: "Mazar",
    cross: "Skunk #1 x Afghani",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [18, 22],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "blueberry-dp",
    name: "Blueberry",
    cross: "1970s Original Blueberry",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [18, 22],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "orange-bud-dp",
    name: "Orange Bud",
    cross: "1980s Original Orange Bud",
    type: "feminized",
    flowering_weeks_range: [7, 8],
    thc_percent_range: [18, 22],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "hollands-hope-dp",
    name: "Hollands Hope",
    cross: "Original Hollands Hope",
    type: "feminized",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [15, 20],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "strawberry-cough-dp",
    name: "Strawberry Cough",
    cross: "Original Strawberry Cough",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [15, 18],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "skunk11-dp",
    name: "Skunk #11",
    cross: "Legendary Skunk #11",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [18, 20],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "euforia-dp",
    name: "Euforia",
    cross: "Euforia Skunk",
    type: "feminized",
    flowering_weeks_range: [8, 10],
    thc_percent_range: [18, 20],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },

  // ---- DUTCH PASSION (autoflowering/reference) ----
  {
    id: "auto-white-widow-dp",
    name: "Auto White Widow",
    cross: "White Widow Autoflower",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [20, 25],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021 (75 dias desde germinacion)",
  },
  {
    id: "auto-mazar-dp",
    name: "Auto Mazar",
    cross: "Mazar x Indica Autoflower",
    type: "autoflowering",
    flowering_weeks_range: [10, 10],
    thc_percent_range: [16, 20],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-blueberry-dp",
    name: "Auto Blueberry",
    cross: "Blueberry x Indica Autoflower",
    type: "autoflowering",
    flowering_weeks_range: [8, 10],
    thc_percent_range: [14, 18],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: medio",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-orange-bud-dp",
    name: "Auto Orange Bud",
    cross: "Orange Bud x Auto Daiquiri Lime",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [18, 22],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-ultimate-dp",
    name: "Auto Ultimate",
    cross: "The Ultimate x Auto Mazar",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [18, 22],
    effect_notes: "Indica / Sativa",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-euforia-dp",
    name: "Auto Euforia",
    cross: "Euforia x Automatic Skunk",
    type: "autoflowering",
    flowering_weeks_range: [11, 11],
    thc_percent_range: [18, 20],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-power-plant-dp",
    name: "Auto Power Plant",
    cross: "Power Plant x Think Different",
    type: "autoflowering",
    flowering_weeks_range: [10, 10],
    thc_percent_range: [18, 20],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "think-different-dp",
    name: "Think Different",
    cross: "AK420 Autoflower",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [18, 22],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-daiquiri-lime-dp",
    name: "Auto Daiquiri Lime",
    cross: "Californian Orange x USA Sour Diesel",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [18, 22],
    effect_notes: "Sativa dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "auto-colorado-cookies-dp",
    name: "Auto Colorado Cookies",
    cross: "Auto Blueberry x Girl Scout Cookies",
    type: "autoflowering",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [18, 22],
    effect_notes: "Indica dominante",
    flavor_notes: "Referencia publicada: extra alto",
    source: "Catalogo Dutch Passion 2021",
  },

  // ---- DUTCH PASSION (CBD-dominant/reference) ----
  {
    id: "cbd-charlottes-angel-dp",
    name: "CBD Charlotte's Angel",
    cross: "Dutch Charlotte x Red Angel",
    type: "feminized",
    flowering_weeks_range: [9, 12],
    thc_percent_range: [0, 1],
    effect_notes: "Sativa dominante - CBD 10-16%",
    flavor_notes: "Herbal, gasolina, pino",
    source: "Catalogo Dutch Passion 2021",
  },
  {
    id: "cbd-skunk-haze-dp",
    name: "CBD Skunk Haze",
    cross: "Haze/Skunk x High CBD variety",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [5, 7.5],
    effect_notes: "Indica / Sativa - CBD aprox. 7.5%",
    flavor_notes: "Suave",
    source: "Catalogo Dutch Passion 2021",
  },

  // ---- HUMBOLDT SEED ORGANIZATION 2025 (static reference) ----
  {
    id: "chem-bomb-auto-hso",
    name: "Chem Bomb Auto",
    cross: "Chem '91 x Bubba Kush Auto",
    type: "autoflowering",
    flowering_weeks_range: [11, 12],
    thc_percent_range: [18, 21],
    effect_notes: "Indica dominant; body and relaxing profile",
    flavor_notes: "Tropical and floral notes",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 75-78)",
  },
  {
    id: "chocolate-mint-og-auto-hso",
    name: "Chocolate Mint OG Auto",
    cross: "Chocolate Mint OG x OG Kush Auto",
    type: "autoflowering",
    flowering_weeks_range: [11, 12],
    thc_percent_range: [18, 21],
    effect_notes: "Indica dominant; relaxing body profile",
    flavor_notes: "Gas, earth, pine, chocolate and mint",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 75-78)",
  },
  {
    id: "mango-og-auto-hso",
    name: "Mango OG Auto",
    cross: "Mango OG Auto selection",
    type: "autoflowering",
    flowering_weeks_range: [11, 12],
    thc_percent_range: [18, 21],
    effect_notes: "Balanced relaxing cerebral and mild body profile",
    flavor_notes: "Spicy mango, pine, black pepper, tropical fruit and floral notes",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 78+)",
  },
  {
    id: "og-kush-auto-hso",
    name: "OG Kush Auto",
    cross: "OG Kush autoflowering selection",
    type: "autoflowering",
    flowering_weeks_range: [11, 11],
    thc_percent_range: [18, 21],
    effect_notes: "Indica dominant; body-focused profile",
    flavor_notes: "Gas, lemon, diesel, pine and lemongrass",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 78)",
  },
  {
    id: "ogkz-auto-hso",
    name: "OGKZ Auto",
    cross: "OGKZ autoflowering selection",
    type: "autoflowering",
    flowering_weeks_range: [11, 12],
    thc_percent_range: [16, 18],
    effect_notes: "Mellow and calming profile",
    flavor_notes: "Sweet and sour candy, peppermint, pine and gas",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 78-83)",
  },
  {
    id: "pineapple-chem-auto-hso",
    name: "Pineapple Chem Auto",
    cross: "Green Crack Auto x Chem Bomb Auto",
    type: "autoflowering",
    flowering_weeks_range: [11, 11],
    thc_percent_range: [18, 21],
    effect_notes: "Mild cerebral and body profile",
    flavor_notes: "Mango, pineapple, berries, gas, floral, pine and citrus",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 78)",
  },
  {
    id: "amherst-sour-diesel-hso",
    name: "Amherst Sour Diesel",
    cross: "Chemdog x Amherst Super Skunk",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [27, 27],
    effect_notes: "Sativa dominant; euphoric and uplifting profile",
    flavor_notes: "Tropical fruit, woody notes, gas and diesel",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 65-70)",
  },
  {
    id: "banana-sapphire-hso",
    name: "Banana Sapphire",
    cross: "Banana OG x Sapphire OG",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [23, 26],
    effect_notes: "Indica dominant; strong cerebral and relaxing body profile",
    flavor_notes: "Gas, black pepper, tropical fruit, banana and mango",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 60-63)",
  },
  {
    id: "blue-dream-hso",
    name: "Blue Dream",
    cross: "Blueberry x selected Haze",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [19, 19],
    effect_notes: "Sativa dominant; clear cerebral profile",
    flavor_notes: "Haze, citrus, cedar, pine, incense and fruit",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 65-70)",
  },
  {
    id: "blueberry-headband-hso",
    name: "Blueberry Headband",
    cross: "Blueberry Headband selection",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [19, 23],
    effect_notes: "Indica dominant; cerebral and physical profile",
    flavor_notes: "Spices, aniseed and fruity notes",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 63-68)",
  },
  {
    id: "chocolate-mint-og-20-hso",
    name: "Chocolate Mint OG 2.0",
    cross: "Emerald OG x Granddaddy Purple",
    type: "feminized",
    flowering_weeks_range: [8, 10],
    thc_percent_range: [22, 26],
    effect_notes: "Indica dominant; relaxing profile",
    flavor_notes: "Chocolate, mint, pine and spices",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 55-65)",
  },
  {
    id: "cinnamon-buddha-og-hso",
    name: "Cinnamon Buddha OG",
    cross: "Triangle/Florida Cut OG x Fire OG",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [21, 24],
    effect_notes: "Indica dominant; strong profile",
    flavor_notes: "Cinnamon, pine, nutmeg, lemon pepper and spices",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 63)",
  },
  {
    id: "dedoverde-haze-hso",
    name: "Dedoverde Haze",
    cross: "Dedoverde Haze selection",
    type: "feminized",
    flowering_weeks_range: [10, 11],
    thc_percent_range: [21, 23],
    effect_notes: "Sativa dominant; bright cerebral profile",
    flavor_notes: "Lime, citrus, pepper, pine, spices, tropical fruit and cedar",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 10-11 weeks)",
  },
  {
    id: "double-fire-headband-hso",
    name: "Double Fire Headband",
    cross: "Fire OG bx3 x Blueberry Headband x III Kings OG",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [21, 24],
    effect_notes: "Sativa dominant; relaxing profile",
    flavor_notes: "Ripe fruit, pine, lemon and hot spices",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 60-65)",
  },
  {
    id: "florida-gaspack-hso",
    name: "Florida Gaspack",
    cross: "Chem '95 x Florida/Triangle OG",
    type: "feminized",
    flowering_weeks_range: [9, 9],
    thc_percent_range: [24, 26],
    effect_notes: "Indica dominant; strong relaxing profile",
    flavor_notes: "Gas, acetone, chemical notes, citrus, pepper, pine and mint",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 60-63)",
  },
  {
    id: "gorilla-breath-hso",
    name: "Gorilla Breath",
    cross: "GG4 x OGKB",
    type: "feminized",
    flowering_weeks_range: [9, 10],
    thc_percent_range: [25, 27],
    effect_notes: "Indica dominant; deeply relaxing profile",
    flavor_notes: "Earth, pine and subtle sweetness",
    source: "Humboldt Seed Organization Catalog 2025 (Indoor Days 60-65)",
  },

  // ---- SWEET SEEDS ES (static reference) ----
  {
    id: "dark-devil-auto-sweet",
    name: "Dark Devil Auto",
    cross: "Big Devil XL Auto x Hindu Kush Auto",
    type: "autoflowering",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [15, 20],
    effect_notes: "Autoflowering red family reference",
    flavor_notes: "Sweet aromatic profile",
    source: "Catalogo Sweet Seeds ES (8.5 weeks from germination)",
  },
  {
    id: "diablo-rojo-xl-auto-sweet",
    name: "Diablo Rojo XL Auto",
    cross: "Dark Devil Auto x Strawberry Cola Auto",
    type: "autoflowering",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [16, 23],
    effect_notes: "Potent, relaxed and imaginative profile",
    flavor_notes: "Sweet, fruity, red fruits, cola, citrus and incense",
    source: "Catalogo Sweet Seeds ES (8 weeks from germination)",
  },
  {
    id: "green-poison-f1-fast-version-sweet",
    name: "Green Poison F1 Fast Version",
    cross: "Green Poison x Green Poison Auto",
    type: "faster_flowering",
    flowering_weeks_range: [6, 6],
    thc_percent_range: [15, 20],
    effect_notes: "Fast flowering version reference",
    flavor_notes: "Sweet and fruity profile",
    source: "Catalogo Sweet Seeds ES (6 weeks flowering)",
  },
  {
    id: "killer-kush-f1-fast-version-sweet",
    name: "Killer Kush F1 Fast Version",
    cross: "OG Kush x Secret 3G Auto",
    type: "faster_flowering",
    flowering_weeks_range: [7, 7],
    thc_percent_range: [18, 25],
    effect_notes: "Fast flowering version reference",
    flavor_notes: "Sweet, citrus, acidic, Chemdawg and Diesel notes",
    source: "Catalogo Sweet Seeds ES (7 weeks flowering)",
  },
  {
    id: "mental-rainbow-f1-fast-version-sweet",
    name: "Mental Rainbow F1 Fast Version",
    cross: "Rainbow Sherbert #11 x Papaya Zoap Auto",
    type: "faster_flowering",
    flowering_weeks_range: [7, 8],
    thc_percent_range: [22, 30],
    effect_notes: "Fast flowering version reference",
    flavor_notes: "Sweet, fruity and tropical profile",
    source: "Catalogo Sweet Seeds ES (7-8 weeks flowering)",
  },
  {
    id: "red-gorilla-girl-xl-auto-sweet",
    name: "Red Gorilla Girl XL Auto",
    cross: "Gorilla Girl XL Auto x Bloody Skunk Auto",
    type: "autoflowering",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [15, 20],
    effect_notes: "Potent and exciting profile",
    flavor_notes: "Citrus, lemon and cypress",
    source: "Catalogo Sweet Seeds ES (8-9 weeks from germination)",
  },
  {
    id: "red-poison-auto-sweet",
    name: "Red Poison Auto",
    cross: "Green Poison x Pakistani Kush Auto",
    type: "autoflowering",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [15, 19],
    effect_notes: "Autoflowering red family reference",
    flavor_notes: "Sweet, fruity and skunk notes",
    source: "Catalogo Sweet Seeds ES (8 weeks from germination)",
  },
  {
    id: "strawberry-cola-sherbet-f1-fast-version-sweet",
    name: "Strawberry Cola Sherbet F1 Fast Version",
    cross: "Sunset Sherbet x Strawberry Cola Auto",
    type: "faster_flowering",
    flowering_weeks_range: [7, 7],
    thc_percent_range: [18, 22],
    effect_notes: "Fast flowering version reference",
    flavor_notes: "Sweet, fruity and cola profile",
    source: "Catalogo Sweet Seeds ES (7 weeks flowering)",
  },
  {
    id: "tropicanna-poison-f1-fast-version-sweet",
    name: "Tropicanna Poison F1 Fast Version",
    cross: "Tropicanna Cookies x Red Poison Auto",
    type: "faster_flowering",
    flowering_weeks_range: [6, 7],
    thc_percent_range: [16, 24],
    effect_notes: "Fast flowering red family reference",
    flavor_notes: "Mango, earthy, woody and skunk notes",
    source: "Catalogo Sweet Seeds ES (6-7 weeks flowering)",
  },
  {
    id: "tropicanna-poison-xl-auto-sweet",
    name: "Tropicanna Poison XL Auto",
    cross: "Tropicanna Cookies x Red Poison Auto",
    type: "autoflowering",
    flowering_weeks_range: [8, 8],
    thc_percent_range: [16, 24],
    effect_notes: "Autoflowering red family reference",
    flavor_notes: "Mango, earthy, woody and skunk notes",
    source: "Catalogo Sweet Seeds ES (8 weeks from germination)",
  },

  // ---- GREEN HOUSE SEED CO. 2023 (static reference) ----
  {
    id: "milky-dreams-ghsc",
    name: "Milky Dreams",
    cross: "Mother's Milk x Persian Pie",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [25, 25],
    effect_notes: "Balanced body and uplifting profile",
    flavor_notes: "Lemon, banana and sweet notes",
    source: "Green House Seed Co. Brochure 2023 Q3 (8-9 weeks indoor flowering)",
  },
  {
    id: "tart-tatin-ghsc",
    name: "Tart Tatin",
    cross: "Caramel Apple Gelato x King's Tart",
    type: "feminized",
    flowering_weeks_range: [8, 9],
    thc_percent_range: [26, 26],
    effect_notes: "Strong, fast body and light head profile",
    flavor_notes: "Caramelized vanilla apple and creamy notes",
    source: "Green House Seed Co. Brochure 2023 Q3 (8-9 weeks indoor flowering)",
  },

  // ---- SEEDFINDER EXCEL - A-B-SEEDS (static reference with original fields) ----
  {
    id: "baseball-bat-a-b-seeds-seedfinder",
    name: "Baseball Bat",
    cross: "Skunk #1",
    type: "regular",
    flowering_weeks_range: [6, 8],
    thc_percent_range: [0, 0],
    effect_notes: "Boa semente para cultivo indoor e outdoor.",
    flavor_notes: "No declarado en Excel",
    source: "SeedFinder Excel - A-B-Seeds",
    raw_fields: {
      Breeder: "A-B-Seeds",
      Variedad: "Baseball Bat",
      "Tipo / herencia": "Mayormente sativa",
      Cultivo: "Interior y exterior",
      "Floracion aproximada": "50 dias",
      "Rango indicado": "45 a 55 dias",
      Feminizada: "No",
      Descripcion: "Boa semente para cultivo indoor e outdoor.",
      "Linaje conocido": "Skunk #1",
      "Fenotipos / imagenes": "9 fenotipos conocidos; sin imagenes cargadas",
      "URL de la variedad": "https://seedfinder.eu/es/strain-info/baseball-bat/a-b-seeds",
      "Fuente breeder": "https://seedfinder.eu/es/database/breeder/a-b-seeds",
    },
  },
  {
    id: "early-pearl-x-northern-light-a-b-seeds-seedfinder",
    name: "Early Pearl x Northern Light",
    cross: "Early Pearl x Northern Lights",
    type: "regular",
    flowering_weeks_range: [6, 8],
    thc_percent_range: [0, 0],
    effect_notes: "Variedad de floracion precoz, resistente a distintas temperaturas, frio y humedad; indicada como apta para principiantes.",
    flavor_notes: "No declarado en Excel",
    source: "SeedFinder Excel - A-B-Seeds",
    raw_fields: {
      Breeder: "A-B-Seeds",
      Variedad: "Early Pearl x Northern Light",
      "Tipo / herencia": "Mayormente indica",
      Cultivo: "Interior y exterior",
      "Floracion aproximada": "50 dias",
      "Rango indicado": "45 a 55 dias",
      Feminizada: "No",
      Descripcion: "Variedad de floracion precoz, resistente a distintas temperaturas, frio y humedad; indicada como apta para principiantes.",
      "Linaje conocido": "Early Pearl x Northern Lights",
      "Fenotipos / imagenes": "2 fenotipos listados; 2 imagenes",
      "URL de la variedad": "https://seedfinder.eu/es/strain-info/early-pearl-x-northern-light/a-b-seeds",
      "Fuente breeder": "https://seedfinder.eu/es/database/breeder/a-b-seeds",
    },
  },
  {
    id: "high-grade-a-b-seeds-seedfinder",
    name: "High-Grade",
    cross: "Variedad desconocida",
    type: "regular",
    flowering_weeks_range: [7, 9],
    thc_percent_range: [0, 0],
    effect_notes: "Boa semente para cultivo indoor e outdoor. O nome ja diz tudo. Germinacao rapida.",
    flavor_notes: "No declarado en Excel",
    source: "SeedFinder Excel - A-B-Seeds",
    raw_fields: {
      Breeder: "A-B-Seeds",
      Variedad: "High-Grade",
      "Tipo / herencia": "Desconocida",
      Cultivo: "Interior y exterior",
      "Floracion aproximada": "55 dias",
      "Rango indicado": "50 a 60 dias",
      Feminizada: "No",
      Descripcion: "Boa semente para cultivo indoor e outdoor. O nome ja diz tudo. Germinacao rapida.",
      "Linaje conocido": "Variedad desconocida",
      "Fenotipos / imagenes": "Sin fenotipos ni imagenes cargadas",
      "URL de la variedad": "https://seedfinder.eu/es/strain-info/high-grade/a-b-seeds",
      "Fuente breeder": "https://seedfinder.eu/es/database/breeder/a-b-seeds",
    },
  },
  {
    id: "presidents-choice-a-b-seeds-seedfinder",
    name: "President's Choice",
    cross: "Early Pearl",
    type: "regular",
    flowering_weeks_range: [6, 8],
    thc_percent_range: [0, 0],
    effect_notes: "Bom para cultivo indoor e outdoor. Resultado das melhores plantas de 2002.",
    flavor_notes: "No declarado en Excel",
    source: "SeedFinder Excel - A-B-Seeds",
    raw_fields: {
      Breeder: "A-B-Seeds",
      Variedad: "President's Choice",
      "Tipo / herencia": "Mayormente sativa",
      Cultivo: "Interior y exterior",
      "Floracion aproximada": "50 dias",
      "Rango indicado": "45 a 55 dias",
      Feminizada: "No",
      Descripcion: "Bom para cultivo indoor e outdoor. Resultado das melhores plantas de 2002.",
      "Linaje conocido": "Early Pearl",
      "Fenotipos / imagenes": "Sin fenotipos ni imagenes cargadas",
      "URL de la variedad": "https://seedfinder.eu/es/strain-info/presidents-choice/a-b-seeds",
      "Fuente breeder": "https://seedfinder.eu/es/database/breeder/a-b-seeds",
    },
  },
];

/** Helper de lectura — NO calcula fechas, solo devuelve el dato de referencia. */
export function getGeneticReference(id: string): GeneticReferenceEntry | undefined {
  return GENETICS_CATALOG.find((g) => g.id === id);
}

export function getGeneticsCatalogAlphabetically(): GeneticReferenceEntry[] {
  return [...GENETICS_CATALOG].sort(compareGeneticNames);
}

export function searchGeneticsByName(query: string): GeneticReferenceEntry[] {
  const q = query.trim().toLowerCase();

  if (q.length < 2) {
    return [];
  }

  return getGeneticsCatalogAlphabetically().filter((g) => {
    const rawText = g.raw_fields ? Object.values(g.raw_fields).join(" ") : "";
    const searchableText = [g.name, g.cross, g.type, g.source, rawText].join(" ").toLowerCase();
    return searchableText.includes(q);
  }).slice(0, 20);
}

function compareGeneticNames(first: GeneticReferenceEntry, second: GeneticReferenceEntry) {
  return first.name.localeCompare(second.name, "es", { sensitivity: "base" });
}
